### ISSUE TITLE
ghdb module: DORKS

### ISSUE THREAD

**Issue by MelissaMV** [s0i37/recon_ng#1]
@s0i37 Hello can you tell me how can I use my own dorks file with the ghdb module?. I see you have the option "DORKS - file containing an alternate list of Google dorks," but I don't see any option or info to upload or use your own dork file.

**Comment by s0i37** [comment]
Hi. You may use some dork-file. It is very simple:
[recon-ng][nbc] > add domains nbc.com
[recon-ng][nbc] > use recon/domains-vulnerabilities/ghdb
[recon-ng][nbc][ghdb] > set DORKS /sdcard/dorks.txt
DORKS => /sdcard/dorks.txt
[recon-ng][nbc][ghdb] > run
But, keep in mind, google has a captcha. Use also ghdb_yahoo.

**Comment by MelissaMV** [comment]
@s0i37 thx mucho :)
